import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export interface AppointmentConfirmationPdfInput {
  firmName: string;
  clientName: string;
  lawyerName: string;
  dateTimeLabel: string;
  endTimeLabel?: string | undefined;
  location?: string | undefined;
  paymentVerifiedLine?: string | undefined;
}

/** Local T3 PDF — never sent to an LLM. Asia/Karachi times are formatted by the caller. */
export async function buildAppointmentConfirmationPdf(
  input: AppointmentConfirmationPdfInput,
): Promise<Buffer> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const { width, height } = page.getSize();
  const ink = rgb(0.12, 0.16, 0.22);
  const muted = rgb(0.35, 0.4, 0.48);
  const accent = rgb(0.12, 0.45, 0.38);

  let y = height - 72;
  page.drawText(input.firmName.slice(0, 80), { x: 56, y, size: 18, font: bold, color: accent });
  y -= 22;
  page.drawText('Appointment confirmation', { x: 56, y, size: 12, font, color: muted });
  y -= 28;
  page.drawLine({ start: { x: 56, y }, end: { x: width - 56, y }, thickness: 1, color: accent });
  y -= 32;

  const rows: Array<[string, string]> = [
    ['Client', input.clientName],
    ['Lawyer', input.lawyerName],
    ['When', input.dateTimeLabel],
  ];
  if (input.endTimeLabel) rows.push(['Ends', input.endTimeLabel]);
  if (input.location) rows.push(['Location', input.location]);
  if (input.paymentVerifiedLine) rows.push(['Payment', input.paymentVerifiedLine]);

  for (const [label, value] of rows) {
    page.drawText(label, { x: 56, y, size: 10, font: bold, color: muted });
    page.drawText(value.slice(0, 90), { x: 180, y, size: 11, font, color: ink });
    y -= 22;
  }

  y -= 16;
  page.drawText('Your appointment is confirmed. Reply on WhatsApp if you need to reschedule.', {
    x: 56,
    y,
    size: 10,
    font,
    color: muted,
  });
  y -= 16;
  page.drawText('Generated by Wakeel.', {
    x: 56,
    y,
    size: 9,
    font,
    color: muted,
  });

  const bytes = await doc.save();
  return Buffer.from(bytes);
}
