-- 0001_init — generated by `prisma migrate diff --from-empty --to-schema`.
-- Hand-added preamble: extensions must exist before any table that uses them
-- (kb_chunks.embedding is vector(1536); appointments' exclusion constraint in
-- 0002 needs btree_gist). Kept here rather than in docker init.sql so
-- non-docker environments (CI, prod) get them from the migration itself.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "app";

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "platform";

-- CreateEnum
CREATE TYPE "platform"."TenantStatus" AS ENUM ('TRIAL', 'ACTIVE', 'SUSPENDED', 'OFFBOARDED');

-- CreateEnum
CREATE TYPE "app"."Language" AS ENUM ('EN', 'UR', 'ROMAN_UR', 'MIXED', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "app"."UserStatus" AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "app"."CaseStatus" AS ENUM ('LEAD', 'CONSULTATION', 'ENGAGED', 'IN_COURT', 'CLOSED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "app"."Urgency" AS ENUM ('LOW', 'NORMAL', 'HIGH', 'CRITICAL');

-- CreateEnum
CREATE TYPE "app"."ConversationState" AS ENUM ('AI_ACTIVE', 'HUMAN_REQUIRED', 'HUMAN_ACTIVE', 'CLOSED');

-- CreateEnum
CREATE TYPE "app"."MessageDirection" AS ENUM ('INBOUND', 'OUTBOUND');

-- CreateEnum
CREATE TYPE "app"."SenderType" AS ENUM ('CLIENT', 'AI', 'LAWYER', 'STAFF', 'SYSTEM');

-- CreateEnum
CREATE TYPE "app"."ContentType" AS ENUM ('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', 'LOCATION', 'INTERACTIVE', 'TEMPLATE', 'STICKER', 'OTHER');

-- CreateEnum
CREATE TYPE "app"."DeliveryStatus" AS ENUM ('QUEUED', 'SENT', 'DELIVERED', 'READ', 'FAILED');

-- CreateEnum
CREATE TYPE "app"."IntakeStatus" AS ENUM ('IN_PROGRESS', 'COMPLETED', 'ABANDONED');

-- CreateEnum
CREATE TYPE "app"."EscalationTrigger" AS ENUM ('SELF_HARM', 'DOMESTIC_VIOLENCE', 'ACTIVE_ARREST', 'IMMINENT_DEADLINE', 'MANUAL');

-- CreateEnum
CREATE TYPE "app"."EscalationStatus" AS ENUM ('OPEN', 'ACKNOWLEDGED', 'RESOLVED');

-- CreateEnum
CREATE TYPE "app"."DocType" AS ENUM ('CNIC', 'FIR', 'COURT_NOTICE', 'AFFIDAVIT', 'CONTRACT', 'EVIDENCE_PHOTO', 'OTHER');

-- CreateEnum
CREATE TYPE "app"."OcrStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "app"."ScanStatus" AS ENUM ('PENDING', 'CLEAN', 'INFECTED', 'FAILED');

-- CreateEnum
CREATE TYPE "app"."DocumentRequestStatus" AS ENUM ('PENDING', 'FULFILLED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "app"."AppointmentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW');

-- CreateEnum
CREATE TYPE "app"."PaymentMethod" AS ENUM ('JAZZCASH', 'EASYPAISA', 'CARD_LOCAL', 'CARD_INTL', 'BANK_TRANSFER', 'CASH', 'OTHER_MANUAL');

-- CreateEnum
CREATE TYPE "app"."PaymentStatus" AS ENUM ('REQUESTED', 'PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'RECORDED_MANUAL', 'CANCELLED');

-- CreateEnum
CREATE TYPE "app"."NotificationChannel" AS ENUM ('DASHBOARD', 'WEB_PUSH', 'WHATSAPP_TEMPLATE');

-- CreateEnum
CREATE TYPE "app"."KbStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "app"."DataTier" AS ENUM ('T1', 'T2', 'T3');

-- CreateEnum
CREATE TYPE "app"."AiCallStatus" AS ENUM ('SUCCESS', 'ERROR', 'FALLBACK_SUCCESS', 'CIRCUIT_OPEN');

-- CreateEnum
CREATE TYPE "app"."WaVerificationStatus" AS ENUM ('NOT_STARTED', 'PENDING', 'VERIFIED', 'REJECTED');

-- CreateEnum
CREATE TYPE "app"."TemplateStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PAUSED');

-- CreateEnum
CREATE TYPE "app"."TemplateCategory" AS ENUM ('UTILITY', 'AUTHENTICATION', 'SERVICE');

-- CreateEnum
CREATE TYPE "app"."ActorType" AS ENUM ('USER', 'SYSTEM', 'PLATFORM_ADMIN', 'AI');

-- CreateEnum
CREATE TYPE "platform"."WebhookEventStatus" AS ENUM ('RECEIVED', 'PROCESSED', 'FAILED', 'DUPLICATE', 'IGNORED');

-- CreateTable
CREATE TABLE "platform"."tenants" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "status" "platform"."TenantStatus" NOT NULL DEFAULT 'TRIAL',
    "settings" JSONB NOT NULL DEFAULT '{}',
    "aiProviderAllowlist" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "aiMonthlyBudgetMicros" INTEGER,
    "retentionDaysOverride" INTEGER,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform"."platform_users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "clerkUserId" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "platform_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform"."permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "code" TEXT NOT NULL,
    "description" TEXT NOT NULL,

    CONSTRAINT "permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform"."prompt_versions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "agent" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "template" TEXT NOT NULL,
    "templateHash" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "prompt_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform"."webhook_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID,
    "provider" TEXT NOT NULL DEFAULT 'meta',
    "externalEventId" TEXT NOT NULL,
    "phoneNumberId" TEXT,
    "payload" JSONB,
    "status" "platform"."WebhookEventStatus" NOT NULL DEFAULT 'RECEIVED',
    "error" TEXT,
    "receivedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMPTZ(6),

    CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "platform"."outbox_events" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL,
    "occurredAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "publishedAt" TIMESTAMPTZ(6),
    "attempts" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "outbox_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."roles" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "isSystem" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."role_permissions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "roleId" UUID NOT NULL,
    "permissionId" UUID NOT NULL,

    CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "clerkUserId" TEXT NOT NULL,
    "roleId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "status" "app"."UserStatus" NOT NULL DEFAULT 'INVITED',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."lawyers" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "practiceAreas" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "whatsappNumber" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "lawyers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."lawyer_availability" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "lawyerId" UUID NOT NULL,
    "weekday" INTEGER NOT NULL,
    "startTime" TEXT NOT NULL,
    "endTime" TEXT NOT NULL,
    "slotDurationMinutes" INTEGER NOT NULL DEFAULT 30,

    CONSTRAINT "lawyer_availability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."clients" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "waPhone" TEXT NOT NULL,
    "name" TEXT,
    "preferredLanguage" "app"."Language" NOT NULL DEFAULT 'UNKNOWN',
    "notes" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."cases" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "clientId" UUID NOT NULL,
    "reference" TEXT NOT NULL,
    "matterType" TEXT NOT NULL,
    "status" "app"."CaseStatus" NOT NULL DEFAULT 'LEAD',
    "urgency" "app"."Urgency" NOT NULL DEFAULT 'NORMAL',
    "summary" TEXT,
    "intakeData" JSONB NOT NULL DEFAULT '{}',
    "openedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "cases_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."case_lawyers" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "caseId" UUID NOT NULL,
    "lawyerId" UUID NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'primary',
    "assignedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "case_lawyers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."conversations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "clientId" UUID NOT NULL,
    "caseId" UUID,
    "state" "app"."ConversationState" NOT NULL DEFAULT 'AI_ACTIVE',
    "language" "app"."Language" NOT NULL DEFAULT 'UNKNOWN',
    "sessionWindowExpiresAt" TIMESTAMPTZ(6),
    "disclosedAt" TIMESTAMPTZ(6),
    "lastClientMessageAt" TIMESTAMPTZ(6),
    "lastOutboundAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."messages" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "conversationId" UUID NOT NULL,
    "direction" "app"."MessageDirection" NOT NULL,
    "senderType" "app"."SenderType" NOT NULL,
    "senderUserId" UUID,
    "wamid" TEXT,
    "contentType" "app"."ContentType" NOT NULL DEFAULT 'TEXT',
    "body" TEXT,
    "languageDetected" "app"."Language" NOT NULL DEFAULT 'UNKNOWN',
    "payload" JSONB NOT NULL DEFAULT '{}',
    "templateName" TEXT,
    "deliveryStatus" "app"."DeliveryStatus" NOT NULL DEFAULT 'QUEUED',
    "citations" JSONB NOT NULL DEFAULT '[]',
    "correlationId" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "messages_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."intake_sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "conversationId" UUID NOT NULL,
    "status" "app"."IntakeStatus" NOT NULL DEFAULT 'IN_PROGRESS',
    "currentStep" TEXT NOT NULL DEFAULT 'start',
    "extractedFields" JSONB NOT NULL DEFAULT '{}',
    "completedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "intake_sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."escalations" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "conversationId" UUID NOT NULL,
    "triggerType" "app"."EscalationTrigger" NOT NULL,
    "status" "app"."EscalationStatus" NOT NULL DEFAULT 'OPEN',
    "detectedExcerpt" TEXT,
    "slaDeadline" TIMESTAMP(3) NOT NULL,
    "acknowledgedBy" UUID,
    "acknowledgedAt" TIMESTAMPTZ(6),
    "resolvedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "escalations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."documents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "caseId" UUID,
    "clientId" UUID NOT NULL,
    "messageId" UUID,
    "storagePath" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "docType" "app"."DocType" NOT NULL DEFAULT 'OTHER',
    "ocrStatus" "app"."OcrStatus" NOT NULL DEFAULT 'PENDING',
    "ocrConfidence" DOUBLE PRECISION,
    "extractedFields" JSONB NOT NULL DEFAULT '{}',
    "scanStatus" "app"."ScanStatus" NOT NULL DEFAULT 'PENDING',
    "version" INTEGER NOT NULL DEFAULT 1,
    "deletedAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."document_requests" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "caseId" UUID NOT NULL,
    "clientId" UUID NOT NULL,
    "description" TEXT NOT NULL,
    "status" "app"."DocumentRequestStatus" NOT NULL DEFAULT 'PENDING',
    "fulfilledDocumentId" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fulfilledAt" TIMESTAMPTZ(6),

    CONSTRAINT "document_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."appointments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "caseId" UUID,
    "clientId" UUID NOT NULL,
    "lawyerId" UUID NOT NULL,
    "startsAt" TIMESTAMPTZ(6) NOT NULL,
    "endsAt" TIMESTAMPTZ(6) NOT NULL,
    "status" "app"."AppointmentStatus" NOT NULL DEFAULT 'PENDING',
    "location" TEXT,
    "notes" TEXT,
    "reminderSentAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."payments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "caseId" UUID,
    "clientId" UUID NOT NULL,
    "amountCents" INTEGER NOT NULL,
    "currency" CHAR(3) NOT NULL DEFAULT 'PKR',
    "method" "app"."PaymentMethod" NOT NULL,
    "status" "app"."PaymentStatus" NOT NULL DEFAULT 'REQUESTED',
    "providerTxnId" TEXT,
    "description" TEXT,
    "requestedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "paidAt" TIMESTAMPTZ(6),
    "recordedBy" UUID,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."notifications" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "type" TEXT NOT NULL,
    "payload" JSONB NOT NULL DEFAULT '{}',
    "channel" "app"."NotificationChannel" NOT NULL DEFAULT 'DASHBOARD',
    "readAt" TIMESTAMPTZ(6),
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."audit_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "actorType" "app"."ActorType" NOT NULL,
    "actorId" UUID,
    "action" TEXT NOT NULL,
    "entityType" TEXT,
    "entityId" UUID,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "ip" INET,
    "userAgent" TEXT,
    "correlationId" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."ai_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "agent" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "promptVersionId" UUID,
    "correlationId" UUID,
    "latencyMs" INTEGER,
    "tokensIn" INTEGER NOT NULL DEFAULT 0,
    "tokensOut" INTEGER NOT NULL DEFAULT 0,
    "costMicros" INTEGER NOT NULL DEFAULT 0,
    "dataTier" "app"."DataTier" NOT NULL,
    "redactionApplied" BOOLEAN NOT NULL DEFAULT false,
    "status" "app"."AiCallStatus" NOT NULL,
    "error" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."prompt_logs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "promptVersionId" UUID NOT NULL,
    "inputRedacted" TEXT NOT NULL,
    "outputRedacted" TEXT NOT NULL,
    "evalScore" DOUBLE PRECISION,
    "correlationId" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "prompt_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."knowledge_base" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "language" "app"."Language" NOT NULL DEFAULT 'EN',
    "category" TEXT,
    "status" "app"."KbStatus" NOT NULL DEFAULT 'DRAFT',
    "sourceDocumentId" UUID,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "knowledge_base_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."kb_chunks" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "kbId" UUID NOT NULL,
    "chunkIndex" INTEGER NOT NULL,
    "content" TEXT NOT NULL,
    "tokenCount" INTEGER NOT NULL,
    "embedding" vector(1536),
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "kb_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."whatsapp_accounts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "wabaId" TEXT NOT NULL,
    "phoneNumberId" TEXT NOT NULL,
    "displayPhoneNumber" TEXT NOT NULL,
    "verificationStatus" "app"."WaVerificationStatus" NOT NULL DEFAULT 'NOT_STARTED',
    "qualityRating" TEXT,
    "messagingTier" TEXT,
    "accessTokenEnc" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "whatsapp_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app"."whatsapp_templates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "tenantId" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "category" "app"."TemplateCategory" NOT NULL,
    "status" "app"."TemplateStatus" NOT NULL DEFAULT 'DRAFT',
    "components" JSONB NOT NULL DEFAULT '{}',
    "metaTemplateId" TEXT,
    "rejectionReason" TEXT,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "whatsapp_templates_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "tenants_slug_key" ON "platform"."tenants"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "platform_users_clerkUserId_key" ON "platform"."platform_users"("clerkUserId");

-- CreateIndex
CREATE UNIQUE INDEX "permissions_code_key" ON "platform"."permissions"("code");

-- CreateIndex
CREATE UNIQUE INDEX "prompt_versions_agent_version_key" ON "platform"."prompt_versions"("agent", "version");

-- CreateIndex
CREATE UNIQUE INDEX "webhook_events_externalEventId_key" ON "platform"."webhook_events"("externalEventId");

-- CreateIndex
CREATE INDEX "webhook_events_status_receivedAt_idx" ON "platform"."webhook_events"("status", "receivedAt");

-- CreateIndex
CREATE INDEX "outbox_events_publishedAt_occurredAt_idx" ON "platform"."outbox_events"("publishedAt", "occurredAt");

-- CreateIndex
CREATE UNIQUE INDEX "roles_tenantId_name_key" ON "app"."roles"("tenantId", "name");

-- CreateIndex
CREATE INDEX "role_permissions_tenantId_idx" ON "app"."role_permissions"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "role_permissions_roleId_permissionId_key" ON "app"."role_permissions"("roleId", "permissionId");

-- CreateIndex
CREATE UNIQUE INDEX "users_clerkUserId_key" ON "app"."users"("clerkUserId");

-- CreateIndex
CREATE INDEX "users_tenantId_status_idx" ON "app"."users"("tenantId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "users_tenantId_email_key" ON "app"."users"("tenantId", "email");

-- CreateIndex
CREATE UNIQUE INDEX "lawyers_userId_key" ON "app"."lawyers"("userId");

-- CreateIndex
CREATE INDEX "lawyers_tenantId_idx" ON "app"."lawyers"("tenantId");

-- CreateIndex
CREATE INDEX "lawyer_availability_tenantId_idx" ON "app"."lawyer_availability"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "lawyer_availability_lawyerId_weekday_startTime_key" ON "app"."lawyer_availability"("lawyerId", "weekday", "startTime");

-- CreateIndex
CREATE UNIQUE INDEX "clients_tenantId_waPhone_key" ON "app"."clients"("tenantId", "waPhone");

-- CreateIndex
CREATE INDEX "cases_tenantId_status_idx" ON "app"."cases"("tenantId", "status");

-- CreateIndex
CREATE INDEX "cases_tenantId_clientId_idx" ON "app"."cases"("tenantId", "clientId");

-- CreateIndex
CREATE UNIQUE INDEX "cases_tenantId_reference_key" ON "app"."cases"("tenantId", "reference");

-- CreateIndex
CREATE INDEX "case_lawyers_tenantId_lawyerId_idx" ON "app"."case_lawyers"("tenantId", "lawyerId");

-- CreateIndex
CREATE UNIQUE INDEX "case_lawyers_caseId_lawyerId_role_key" ON "app"."case_lawyers"("caseId", "lawyerId", "role");

-- CreateIndex
CREATE INDEX "conversations_tenantId_state_idx" ON "app"."conversations"("tenantId", "state");

-- CreateIndex
CREATE INDEX "conversations_tenantId_clientId_idx" ON "app"."conversations"("tenantId", "clientId");

-- CreateIndex
CREATE INDEX "messages_conversationId_createdAt_idx" ON "app"."messages"("conversationId", "createdAt");

-- CreateIndex
CREATE INDEX "messages_tenantId_createdAt_idx" ON "app"."messages"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "messages_wamid_idx" ON "app"."messages"("wamid");

-- CreateIndex
CREATE INDEX "intake_sessions_tenantId_status_idx" ON "app"."intake_sessions"("tenantId", "status");

-- CreateIndex
CREATE INDEX "escalations_tenantId_status_idx" ON "app"."escalations"("tenantId", "status");

-- CreateIndex
CREATE INDEX "documents_tenantId_caseId_idx" ON "app"."documents"("tenantId", "caseId");

-- CreateIndex
CREATE INDEX "documents_tenantId_clientId_idx" ON "app"."documents"("tenantId", "clientId");

-- CreateIndex
CREATE INDEX "document_requests_tenantId_status_idx" ON "app"."document_requests"("tenantId", "status");

-- CreateIndex
CREATE INDEX "appointments_tenantId_lawyerId_startsAt_idx" ON "app"."appointments"("tenantId", "lawyerId", "startsAt");

-- CreateIndex
CREATE INDEX "appointments_tenantId_clientId_idx" ON "app"."appointments"("tenantId", "clientId");

-- CreateIndex
CREATE INDEX "payments_tenantId_status_idx" ON "app"."payments"("tenantId", "status");

-- CreateIndex
CREATE INDEX "payments_tenantId_caseId_idx" ON "app"."payments"("tenantId", "caseId");

-- CreateIndex
CREATE INDEX "notifications_tenantId_userId_readAt_idx" ON "app"."notifications"("tenantId", "userId", "readAt");

-- CreateIndex
CREATE INDEX "audit_logs_tenantId_createdAt_idx" ON "app"."audit_logs"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "audit_logs_tenantId_entityType_entityId_idx" ON "app"."audit_logs"("tenantId", "entityType", "entityId");

-- CreateIndex
CREATE INDEX "ai_logs_tenantId_createdAt_idx" ON "app"."ai_logs"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "ai_logs_correlationId_idx" ON "app"."ai_logs"("correlationId");

-- CreateIndex
CREATE INDEX "prompt_logs_tenantId_createdAt_idx" ON "app"."prompt_logs"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "knowledge_base_tenantId_status_idx" ON "app"."knowledge_base"("tenantId", "status");

-- CreateIndex
CREATE INDEX "kb_chunks_tenantId_kbId_idx" ON "app"."kb_chunks"("tenantId", "kbId");

-- CreateIndex
CREATE UNIQUE INDEX "whatsapp_accounts_tenantId_key" ON "app"."whatsapp_accounts"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "whatsapp_accounts_phoneNumberId_key" ON "app"."whatsapp_accounts"("phoneNumberId");

-- CreateIndex
CREATE INDEX "whatsapp_templates_tenantId_status_idx" ON "app"."whatsapp_templates"("tenantId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "whatsapp_templates_tenantId_name_language_key" ON "app"."whatsapp_templates"("tenantId", "name", "language");

-- AddForeignKey
ALTER TABLE "platform"."webhook_events" ADD CONSTRAINT "webhook_events_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "platform"."outbox_events" ADD CONSTRAINT "outbox_events_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."roles" ADD CONSTRAINT "roles_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."role_permissions" ADD CONSTRAINT "role_permissions_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "app"."roles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."role_permissions" ADD CONSTRAINT "role_permissions_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "platform"."permissions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."users" ADD CONSTRAINT "users_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."users" ADD CONSTRAINT "users_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "app"."roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."lawyers" ADD CONSTRAINT "lawyers_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."lawyers" ADD CONSTRAINT "lawyers_userId_fkey" FOREIGN KEY ("userId") REFERENCES "app"."users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."lawyer_availability" ADD CONSTRAINT "lawyer_availability_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."lawyer_availability" ADD CONSTRAINT "lawyer_availability_lawyerId_fkey" FOREIGN KEY ("lawyerId") REFERENCES "app"."lawyers"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."clients" ADD CONSTRAINT "clients_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."cases" ADD CONSTRAINT "cases_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."cases" ADD CONSTRAINT "cases_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "app"."clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."case_lawyers" ADD CONSTRAINT "case_lawyers_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."case_lawyers" ADD CONSTRAINT "case_lawyers_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "app"."cases"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."case_lawyers" ADD CONSTRAINT "case_lawyers_lawyerId_fkey" FOREIGN KEY ("lawyerId") REFERENCES "app"."lawyers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."conversations" ADD CONSTRAINT "conversations_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."conversations" ADD CONSTRAINT "conversations_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "app"."clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."conversations" ADD CONSTRAINT "conversations_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "app"."cases"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."messages" ADD CONSTRAINT "messages_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."messages" ADD CONSTRAINT "messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "app"."conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."intake_sessions" ADD CONSTRAINT "intake_sessions_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."intake_sessions" ADD CONSTRAINT "intake_sessions_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "app"."conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."escalations" ADD CONSTRAINT "escalations_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."escalations" ADD CONSTRAINT "escalations_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "app"."conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."escalations" ADD CONSTRAINT "escalations_acknowledgedBy_fkey" FOREIGN KEY ("acknowledgedBy") REFERENCES "app"."lawyers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."documents" ADD CONSTRAINT "documents_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."documents" ADD CONSTRAINT "documents_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "app"."cases"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."documents" ADD CONSTRAINT "documents_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "app"."clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."document_requests" ADD CONSTRAINT "document_requests_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."appointments" ADD CONSTRAINT "appointments_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."appointments" ADD CONSTRAINT "appointments_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "app"."cases"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."appointments" ADD CONSTRAINT "appointments_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "app"."clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."appointments" ADD CONSTRAINT "appointments_lawyerId_fkey" FOREIGN KEY ("lawyerId") REFERENCES "app"."lawyers"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payments" ADD CONSTRAINT "payments_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payments" ADD CONSTRAINT "payments_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "app"."cases"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."payments" ADD CONSTRAINT "payments_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "app"."clients"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."notifications" ADD CONSTRAINT "notifications_userId_fkey" FOREIGN KEY ("userId") REFERENCES "app"."users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."audit_logs" ADD CONSTRAINT "audit_logs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."ai_logs" ADD CONSTRAINT "ai_logs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."ai_logs" ADD CONSTRAINT "ai_logs_promptVersionId_fkey" FOREIGN KEY ("promptVersionId") REFERENCES "platform"."prompt_versions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."prompt_logs" ADD CONSTRAINT "prompt_logs_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."prompt_logs" ADD CONSTRAINT "prompt_logs_promptVersionId_fkey" FOREIGN KEY ("promptVersionId") REFERENCES "platform"."prompt_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."knowledge_base" ADD CONSTRAINT "knowledge_base_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."kb_chunks" ADD CONSTRAINT "kb_chunks_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."kb_chunks" ADD CONSTRAINT "kb_chunks_kbId_fkey" FOREIGN KEY ("kbId") REFERENCES "app"."knowledge_base"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_accounts" ADD CONSTRAINT "whatsapp_accounts_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app"."whatsapp_templates" ADD CONSTRAINT "whatsapp_templates_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "platform"."tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

